name       : pluma
version    : 1.18.2
release    : 6
source     :
    - https://pub.mate-desktop.org/releases/1.18/pluma-1.18.2.tar.xz : ff0f29d4eaa946cbb2b26bbdc2b2d5a308b2d16ec99ea384bcb13f1f3d1a09fc
license    : GPL-2.0
component  : desktop.mate
summary    : Text Editor for the MATE Desktop
description: |
    Text Editor for the MATE Desktop
builddeps  :
    - pkgconfig(enchant)
    - pkgconfig(gmodule-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gtksourceview-3.0)
    - pkgconfig(libpeas-1.0)
    - pkgconfig(libpeas-gtk-1.0)
    - pkgconfig(mate-desktop-2.0)
    - pkgconfig(pygobject-2.0)
    - pkgconfig(pygtk-2.0)
    - pkgconfig(sm)
    - pkgconfig(x11)
    - itstool
setup      : |
    %configure --with-gtk=3.0
build      : |
    %make
install    : |
    %make_install
