name       : pluma
version    : 1.20.1
release    : 9
source     :
    - https://pub.mate-desktop.org/releases/1.20/pluma-1.20.1.tar.xz : e346d447b376537eb7f8937a7b1cfd15eee983d516e3d0fafd019bdfaeff5925
license    : GPL-2.0-only
component  : desktop.mate
summary    : Text Editor for the MATE Desktop
description: |
    Text Editor for the MATE Desktop
builddeps  :
    - pkgconfig(enchant)
    - pkgconfig(gmodule-2.0)
    - pkgconfig(gtksourceview-3.0)
    - pkgconfig(libpeas-1.0)
    - pkgconfig(mate-desktop-2.0)
    - pkgconfig(pygobject-2.0)
    - pkgconfig(pygtk-2.0)
    - pkgconfig(sm)
    - pkgconfig(x11)
    - itstool
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
