name       : pluma
version    : 1.27.0
release    : 31
source     :
    - https://github.com/mate-desktop/pluma/releases/download/v1.27.0/pluma-1.27.0.tar.xz : b8ebec523f8eabd93742b936d707b8a8d407ba0493312399229ab9789ddc70e2
license    : GPL-2.0-or-later
component  : desktop.mate
summary    : Text Editor for the MATE Desktop
description: |
    pluma is a small and lightweight UTF-8 text editor for the MATE environment. Based on gedit, the text editor for the GNOME2 environment.
builddeps  :
    - pkgconfig(enchant-2)
    - pkgconfig(gtk-doc)
    - pkgconfig(gtksourceview-4)
    - pkgconfig(libpeas-1.0)
    - pkgconfig(mate-desktop-2.0)
    - pkgconfig(pygobject-3.0)
    - pkgconfig(sm)
    - itstool
setup      : |
    %configure --enable-gtk-doc --disable-tests
build      : |
    %make
install    : |
    %make_install
