name       : pluma
version    : 1.22.1
release    : 16
source     :
    - https://github.com/mate-desktop/pluma/archive/v1.22.1.tar.gz : 402a7071c1616d0100b8f2fd1e6d713fb136bc5d8d22724c4ea5b3a5a3830477
license    : GPL-2.0-or-later
component  : desktop.mate
summary    : Text Editor for the MATE Desktop
description: |
    pluma is a small and lightweight UTF-8 text editor for the MATE environment. Based on gedit, the text editor for the GNOME2 environment.
builddeps  :
    - pkgconfig(enchant-2)
    - pkgconfig(gtk-doc)
    - pkgconfig(gtksourceview-3.0)
    - pkgconfig(libpeas-1.0)
    - pkgconfig(mate-desktop-2.0)
    - pkgconfig(pygobject-3.0)
    - pkgconfig(sm)
    - itstool
    - mate-common
    - yelp-tools
setup      : |
    %autogen --enable-gtk-doc --disable-tests
build      : |
    %make
install    : |
    %make_install
