name       : pluma
version    : 1.18.1
release    : 4
source     :
    - https://pub.mate-desktop.org/releases/1.18/pluma-1.18.1.tar.xz : 3ad4ef5c67ee0edef15e4549b1d9de49bd106b551a5b6d17517860ad413873b6
license    : GPL-2.0
component  : desktop.mate
summary    : Text Editor for the MATE Desktop
description: |
    Text Editor for the MATE Desktop
builddeps  :
    - itstool
    - pkgconfig(enchant)
    - pkgconfig(gmodule-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gtksourceview-3.0)
    - pkgconfig(libpeas-1.0)
    - pkgconfig(libpeas-gtk-1.0)
    - pkgconfig(mate-desktop-2.0)
    - pkgconfig(pygobject-2.0)
    - pkgconfig(pygtk-2.0)
    - pkgconfig(sm)
    - pkgconfig(x11)
setup      : |
    %configure --with-gtk=3.0
build      : |
    %make
install    : |
    %make_install
