name       : pluma
version    : 1.20.0
release    : 8
source     :
    - https://pub.mate-desktop.org/releases/1.20/pluma-1.20.0.tar.xz : aee0072dea73135b391dd4cb192fee9cd9c7a0639e3616c4502e8760c1115d70
license    : GPL-2.0
component  : desktop.mate
summary    : Text Editor for the MATE Desktop
description: |
    Text Editor for the MATE Desktop
builddeps  :
    - pkgconfig(enchant)
    - pkgconfig(gmodule-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gtksourceview-3.0)
    - pkgconfig(libpeas-1.0)
    - pkgconfig(libpeas-gtk-1.0)
    - pkgconfig(mate-desktop-2.0)
    - pkgconfig(pygobject-2.0)
    - pkgconfig(pygtk-2.0)
    - pkgconfig(sm)
    - pkgconfig(x11)
    - itstool
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
