name       : pluma
version    : 1.22.2
release    : 18
source     :
    - https://github.com/mate-desktop/pluma/archive/v1.22.2.tar.gz : c534bc3a64a8f13081dd20c4d27acba7be73755dee807d17a85dc2d01cea5094
license    : GPL-2.0-or-later
component  : desktop.mate
summary    : Text Editor for the MATE Desktop
description: |
    pluma is a small and lightweight UTF-8 text editor for the MATE environment. Based on gedit, the text editor for the GNOME2 environment.
builddeps  :
    - pkgconfig(enchant-2)
    - pkgconfig(gtk-doc)
    - pkgconfig(gtksourceview-3.0)
    - pkgconfig(libpeas-1.0)
    - pkgconfig(mate-desktop-2.0)
    - pkgconfig(pygobject-3.0)
    - pkgconfig(sm)
    - itstool
    - mate-common
    - yelp-tools
setup      : |
    %autogen --enable-gtk-doc --disable-tests
build      : |
    %make
install    : |
    %make_install
