name       : pluma
version    : 1.14.1
release    : 1
source     :
    - http://pub.mate-desktop.org/releases/1.14/pluma-1.14.1.tar.xz : 5517e9bf93ec22a3036498f2e95652fb9046229b8a0da66a742643eab7e595a1
license    : GPL-2.0
component  : desktop.mate
summary    : Text Editor for the MATE Desktop
description: |
    Text Editor for the MATE Desktop
builddeps  :
    - pkgconfig(enchant)
    - pkgconfig(gmodule-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gtksourceview-3.0)
    - pkgconfig(mate-desktop-2.0)
    - pkgconfig(pygobject-2.0)
    - pkgconfig(pygtk-2.0)
    - pkgconfig(x11)
    - pkgconfig(sm)
    - itstool
setup      : |
    %configure --with-gtk=3.0
build      : |
    %make
install    : |
    %make_install
